### ISSUE TITLE
Редактирование категорий

### ISSUE THREAD

**Issue by Diplomat-1** [abricos/abricos-mod-money#1]
Возможность удаления категорий, подкатегорий их редактирования (сейчас только можно
добавлять категории)Возможность удаления категорий, подкатегорий их редактирования (сейчас только можно добавлять категории)

**Comment by roosit** [comment]
Реализовано в версии 0.2.1

**Comment by Diplomat-1** [comment]
как установить версию 0.2.1?

**Comment by roosit** [comment]
Пока ее установить невозможно, так как полностью перерабатываю модуль под новую версию ядра 0.5.7
Планирую выпустить не модуль, а сборку, заточенную под управления финансами. Сама сборка доступна здесь: https://github.com/abricos/abricos-person , так же там будет доступен и дистрибутив для скачивания.
Осталось переработать 15%. Вот здесь хронология событий работы по модулю https://github.com/abricos/abricos-mod-money/commits/0.2.1
Если все пойдет по плану, выход бета версии запланирован на начало сентября, возможно и раньше

**Comment by Diplomat-1** [comment]
блин, я что-то наковырял и у меня пропал модуль финансы, поднял полностью backup за вчерашний день, но модуль на главной странице все равно не отображается. Подскажите в чем может быть проблема?

**Comment by Diplomat-1** [comment]
при вводе http://abricos.skmash.ru/bos/#app=money/wspace/ws/about/AccessDeniedWidget/ пишет, что доступ запрещен У вас недостаточно прав, или необходимо зарегистрироваться. Хотя я уже в системе зарегистрирован

**Comment by roosit** [comment]
давайте не будем засорять тикеты, это общие вопросы, адресуйте их или на форум или в новый тикет

**Comment by Diplomat-1** [comment]
ок, сори, нашел решение, изменил installdate в phpmyadmin в таблице cms_module аналогичное остальным модулям и все заработало.
