### ISSUE TITLE
разделение по тысячным в форме ввода значения операции

### ISSUE THREAD

**Issue by ildarkhasanshin** [abricos/abricos-mod-money#10]
1
при вводе суммы
сейчас так: 1234567890
должно быть так: 1 234 567 890

2
в журнале операций
в списке нет разделения по тысячным
хотя в итоговой сумме есть
https://dl.dropboxusercontent.com/u/84053743/shots/_92_150831223614.png

тестировал на 0.2.1beta

**Comment by roosit** [comment]
баг 2 был в форматировании числа 1000, это видно даже по скриншоту
P.S. одна задача, один тикет
