### ISSUE TITLE
Визуальное отображение

### ISSUE THREAD

**Issue by Diplomat-1** [abricos/abricos-mod-money#4]
Возможность включения визуального отображения доходов и расходов
(график, можно в виде круга) за определенный период (день, неделя,
месяц, произвольный) в разрезе категорий по каждому счету отдельно и с
возможностью выборки нескольких счетов. 
Например:
![grafik](https://cloud.githubusercontent.com/assets/1107325/8962941/3a46a686-3626-11e5-8ff7-6fe940c405ed.jpeg)

**Comment by ildarkhasanshin** [comment]
+1

**Comment by roosit** [comment]
Есть мысли как отображать несколько счетов с разными валютами?

**Comment by roosit** [comment]
![piechart](https://cloud.githubusercontent.com/assets/1107325/10122043/1132aebe-6512-11e5-9032-7469429b3422.png)
